using Haley.Models;
using Kida.Abstractions;
using Kida.Constants;
using Kida.Models;
using Kida.Utils;
namespace Kida.Service.Client;
public interface IKidaClient
{
    ValueTask<AuthenticationResult> AuthenticateAsync(AuthenticateRequest request, CancellationToken cancellationToken = default);
    ValueTask<PasswordlessAuthenticationInitiationResult> BeginPasswordlessAuthenticationAsync(BeginPasswordlessAuthenticationRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<PasswordlessAuthenticationInitiationResult>(new NotSupportedException());
    ValueTask<PasswordlessAuthenticationResult> CompletePasswordlessAuthenticationAsync(CompletePasswordlessAuthenticationRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<PasswordlessAuthenticationResult>(new NotSupportedException());
    ValueTask<AuthenticationResult> RefreshSessionAsync(string refreshToken, CancellationToken cancellationToken = default);
    ValueTask RevokeSessionAsync(Guid sessionId, CancellationToken cancellationToken = default);
    ValueTask<ProvisionedUser> ProvisionUserAsync(ProvisionLocalUserRequest request, CancellationToken cancellationToken = default);
    ValueTask<IdentityInvitationReceipt> InviteUserAsync(InviteIdentityRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<IdentityInvitationReceipt>(new NotSupportedException());
    ValueTask<ProvisionedUser> BootstrapUserAsync(BootstrapIdentityRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<ProvisionedUser>(new NotSupportedException());
    ValueTask<IdentityInvitationReceipt> MigrateLegacyUserAsync(MigrateLegacyIdentityRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<IdentityInvitationReceipt>(new NotSupportedException());
    ValueTask<VerificationGrantReceipt> VerifyInvitationAsync(VerifyIdentityInvitationRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<VerificationGrantReceipt>(new NotSupportedException());
    ValueTask<UserIdentity> CompleteEnrollmentAsync(CompleteIdentityEnrollmentRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<UserIdentity>(new NotSupportedException());
    ValueTask<FederatedIdentityResult> RedeemFederationHandoffAsync(RedeemFederationHandoffRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<FederatedIdentityResult>(new NotSupportedException());
    ValueTask<UserIdentity?> ResolveUserAsync(string username, CancellationToken cancellationToken = default);
    ValueTask<UserLoginAttemptPage> ListUserLoginAttemptsAsync(Guid userId, int page = 1, int pageSize = 10, CancellationToken cancellationToken = default) => ValueTask.FromException<UserLoginAttemptPage>(new NotSupportedException());
    ValueTask SetUserStatusAsync(Guid userId, SetUserStatusRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask ReleaseUserLoginProtectionAsync(Guid userId, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask ResetUserPasswordAsync(Guid userId, ResetUserPasswordRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask ChangePasswordAsync(ChangePasswordRequest request, CancellationToken cancellationToken = default);
    ValueTask<PasswordResetInitiationResult> BeginPasswordResetAsync(ClientPasswordResetRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<PasswordResetInitiationResult>(new NotSupportedException());
    ValueTask<OAuthScopeRegistrationResult> RegisterScopesAsync(RegisterOAuthScopesRequest request, CancellationToken cancellationToken = default);
    ValueTask<AccessResult> RegisterModuleAsync(RegisterModuleRequest request, CancellationToken cancellationToken = default);
    ValueTask<IReadOnlyCollection<AccessModuleInfo>> ListModulesAsync(CancellationToken cancellationToken = default) => ValueTask.FromException<IReadOnlyCollection<AccessModuleInfo>>(new NotSupportedException());
    ValueTask<AccessDecision> EvaluateAccessAsync(AccessDecisionRequest request, CancellationToken cancellationToken = default);
    ValueTask<AccessPolicyVersionInfo> GetAccessPolicyVersionAsync(Guid tenantId, string module, CancellationToken cancellationToken = default);
    ValueTask<AccessPolicySnapshot> GetAccessPolicySnapshotAsync(Guid tenantId, string module, CancellationToken cancellationToken = default);
    ValueTask<AccessPolicyDefinitionSnapshot> GetAccessPolicyDefinitionAsync(Guid tenantId, string module, CancellationToken cancellationToken = default) => ValueTask.FromException<AccessPolicyDefinitionSnapshot>(new NotSupportedException());
    ValueTask<SubjectEntitlementRevisionInfo> GetSubjectEntitlementRevisionAsync(Guid tenantId, SubjectEntitlementQuery request, CancellationToken cancellationToken = default) => ValueTask.FromException<SubjectEntitlementRevisionInfo>(new NotSupportedException());
    ValueTask<SubjectEntitlementSnapshot> GetSubjectEntitlementSnapshotAsync(Guid tenantId, SubjectEntitlementQuery request, CancellationToken cancellationToken = default) => ValueTask.FromException<SubjectEntitlementSnapshot>(new NotSupportedException());
    ValueTask<ClientResourceGrantSnapshot> GetClientResourceGrantSnapshotAsync(Guid clientId, string resource, CancellationToken cancellationToken = default) => ValueTask.FromException<ClientResourceGrantSnapshot>(new NotSupportedException());
    async ValueTask<ClientResourceGrantRevision> GetClientResourceGrantRevisionAsync(Guid clientId, string resource, CancellationToken cancellationToken = default)
    {
        var snapshot = await GetClientResourceGrantSnapshotAsync(clientId, resource, cancellationToken).ConfigureAwait(false);
        return new(snapshot.ClientId, snapshot.Audience, snapshot.Status, snapshot.Version, snapshot.RevisionHash, snapshot.ModifiedAt);
    }
    ValueTask<IReadOnlyCollection<AccessRoleInfo>> ListRolesAsync(Guid tenantId, CancellationToken cancellationToken = default);
    ValueTask<AccessResult> CreateRoleAsync(CreateRoleRequest request, CancellationToken cancellationToken = default);
    ValueTask GrantRoleActionAsync(GrantRoleActionRequest request, CancellationToken cancellationToken = default);
    ValueTask ApplyRoleActionsAsync(ApplyRoleActionsRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask EnsureRoleActionAsync(EnsureRoleActionRequest request, CancellationToken cancellationToken = default);
    ValueTask<IReadOnlyCollection<RoleAssignmentInfo>> ListAssignmentsAsync(Guid tenantId, CancellationToken cancellationToken = default);
    ValueTask<AccessResult> AssignRoleAsync(AssignRoleRequest request, CancellationToken cancellationToken = default);
    ValueTask RevokeRoleAssignmentAsync(Guid tenantId, Guid assignmentId, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<TenantPage> SearchTenantsAsync(TenantSearchRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantPage>(new NotSupportedException());
    ValueTask<TenantSummary> CreateTenantAsync(CreateTenantRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantSummary>(new NotSupportedException());
    ValueTask<TenantSummary> UpdateTenantAsync(Guid tenantId, UpdateTenantRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantSummary>(new NotSupportedException());
    ValueTask<TenantAdministrationSnapshot> InspectTenantAsync(Guid tenantId, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantAdministrationSnapshot>(new NotSupportedException());
    ValueTask<TenantDomainInfo> AddTenantDomainAsync(AddTenantDomainRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantDomainInfo>(new NotSupportedException());
    ValueTask RemoveTenantDomainAsync(Guid tenantId, Guid domainId, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<TenantMembershipInfo> SetTenantMembershipAsync(SetTenantMembershipRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantMembershipInfo>(new NotSupportedException());
    ValueTask RemoveTenantMembershipAsync(Guid tenantId, Guid membershipId, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<TenantInvitationReceipt> CreateTenantInvitationAsync(CreateTenantInvitationRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantInvitationReceipt>(new NotSupportedException());
    ValueTask RevokeTenantInvitationAsync(Guid tenantId, Guid invitationId, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<TenantSettingInfo> SetTenantSettingAsync(SetTenantSettingRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantSettingInfo>(new NotSupportedException());
    ValueTask RemoveTenantSettingAsync(Guid tenantId, string key, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<IReadOnlyCollection<DeploymentInfo>> ListDeploymentsAsync(CancellationToken cancellationToken = default) => ValueTask.FromException<IReadOnlyCollection<DeploymentInfo>>(new NotSupportedException());
    ValueTask<DeploymentInfo> CreateDeploymentAsync(CreateDeploymentRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<DeploymentInfo>(new NotSupportedException());
    ValueTask<TenantDeploymentInfo> AssignTenantDeploymentAsync(AssignTenantDeploymentRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TenantDeploymentInfo>(new NotSupportedException());
    ValueTask UnassignTenantDeploymentAsync(Guid tenantId, Guid deploymentId, string familyCode, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<EntitlementCatalogReceipt> RegisterEntitlementCatalogAsync(RegisterEntitlementCatalogRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<EntitlementCatalogReceipt>(new NotSupportedException());
    ValueTask<EntitlementProductCatalog> GetEntitlementProductAsync(string productCode, CancellationToken cancellationToken = default) => ValueTask.FromException<EntitlementProductCatalog>(new NotSupportedException());
    ValueTask<IReadOnlyCollection<EntitlementSubscriptionInfo>> GetTenantEntitlementSubscriptionsAsync(Guid tenantId, string productCode, CancellationToken cancellationToken = default) => ValueTask.FromException<IReadOnlyCollection<EntitlementSubscriptionInfo>>(new NotSupportedException());
    ValueTask<EntitlementSubscriptionPage> GetTenantEntitlementSubscriptionHistoryAsync(Guid tenantId, string productCode, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default) => ValueTask.FromException<EntitlementSubscriptionPage>(new NotSupportedException());
    ValueTask<EntitlementPlanInfo> CreateEntitlementPlanAsync(CreateEntitlementPlanRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<EntitlementPlanInfo>(new NotSupportedException());
    ValueTask<EntitlementSubscriptionInfo> CreateEntitlementSubscriptionAsync(CreateSubscriptionRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<EntitlementSubscriptionInfo>(new NotSupportedException());
    ValueTask<EntitlementDecision> EvaluateEntitlementAsync(EvaluateEntitlementRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<EntitlementDecision>(new NotSupportedException());
    ValueTask<UsageReceipt> ReportEntitlementUsageAsync(ReportUsageRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<UsageReceipt>(new NotSupportedException());
    ValueTask<LicenseLeaseReceipt> AcquireLicenseAsync(AcquireLicenseRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<LicenseLeaseReceipt>(new NotSupportedException());
    ValueTask<LicenseLeaseReceipt> HeartbeatLicenseAsync(HeartbeatLicenseRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<LicenseLeaseReceipt>(new NotSupportedException());
    ValueTask ReleaseLicenseAsync(ReleaseLicenseRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<AppCatalogReceipt> RegisterAppCatalogAsync(RegisterAppCatalogRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<AppCatalogReceipt>(new NotSupportedException());
    ValueTask<AppPage> SearchAppsAsync(string? query = null, AppStatus? status = null, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default) => ValueTask.FromException<AppPage>(new NotSupportedException());
    ValueTask<AppInstallationInfo> InstallAppAsync(InstallAppRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<AppInstallationInfo>(new NotSupportedException());
    ValueTask<IReadOnlyCollection<AppInstallationInfo>> ListAppInstallationsAsync(Guid tenantId, string hostAudience, CancellationToken cancellationToken = default) => ValueTask.FromException<IReadOnlyCollection<AppInstallationInfo>>(new NotSupportedException());
    ValueTask<AppComposition> ComposeAppsAsync(Guid tenantId, Guid? projectId, string hostAudience, CancellationToken cancellationToken = default) => ValueTask.FromException<AppComposition>(new NotSupportedException());
    ValueTask ReportAppHealthAsync(ReportAppHealthRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException(new NotSupportedException());
    ValueTask<UserIdentity> GetCurrentUserAsync(string userAccessToken, CancellationToken cancellationToken = default);
    ValueTask<UserProfile> GetProfileAsync(string userAccessToken, CancellationToken cancellationToken = default);
    ValueTask<UserProfile> UpdateProfileAsync(string userAccessToken, UpdateUserProfileRequest request, CancellationToken cancellationToken = default);
    ValueTask<IReadOnlyCollection<MfaMethodInfo>> ListMfaMethodsAsync(string userAccessToken, CancellationToken cancellationToken = default) => ValueTask.FromException<IReadOnlyCollection<MfaMethodInfo>>(new NotSupportedException());
    ValueTask<TotpEnrollmentReceipt> BeginTotpEnrollmentAsync(string userAccessToken, ClientTotpEnrollmentRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<TotpEnrollmentReceipt>(new NotSupportedException());
    ValueTask<RecoveryCodesReceipt> ReplaceRecoveryCodesAsync(string userAccessToken, ReplaceRecoveryCodesRequest request, CancellationToken cancellationToken = default) => ValueTask.FromException<RecoveryCodesReceipt>(new NotSupportedException());
}
