<Project Sdk="Microsoft.NET.Sdk">
  <Choose>
    <When Condition="'$(KidaUseHaleyPackageReferences)' == 'false'">
      <ItemGroup>
        <ProjectReference Include="$(HaleyAbstractions)\HaleyAbstractions.csproj"><Name>HaleyAbstractions</Name></ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup><PackageReference Include="Haley.Abstractions" /></ItemGroup>
    </Otherwise>
  </Choose>
</Project>
