<Project Sdk="Microsoft.NET.Sdk">
  <Choose>
    <When Condition="'$(KidaUseHaleyPackageReferences)' == 'false'">
      <ItemGroup>
        <ProjectReference Include="$(HaleyAbstractions)\HaleyAbstractions.csproj"><Name>HaleyAbstractions</Name></ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup><PackageReference Include="Haley.Abstractions" /></ItemGroup>
    </Otherwise>
  </Choose>
  <Choose>
    <When Condition="'$(KidaUseHaleyPackageReferences)' == 'false'">
      <ItemGroup>
        <ProjectReference Include="$(HaleyExtensions)\HaleyExtensions.csproj"><Name>HaleyExtensions</Name></ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup><PackageReference Include="Haley.Extensions" /></ItemGroup>
    </Otherwise>
  </Choose>
  <Choose>
    <When Condition="'$(KidaUseHaleyPackageReferences)' == 'false'">
      <ItemGroup>
        <ProjectReference Include="$(HaleyHelpers)\HaleyHelpers.csproj"><Name>HaleyHelpers</Name></ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup><PackageReference Include="Haley.Helpers" /></ItemGroup>
    </Otherwise>
  </Choose>
</Project>
